spring.application.name=event-relay

spring.datasource.url=jdbc:postgresql://localhost:5432/eventrelay
spring.datasource.username=eventrelay
spring.datasource.password=devpassword

spring.jpa.hibernate.ddl-auto=update